<a href="https://colab.research.google.com/github/mehrnazh/PythonVisualization/blob/main/Review_of_Day_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



---

### Python Lists

A **list** is a built-in Python data type that represents an ordered collection of items, which can be of any type. Lists are mutable, meaning their elements can be changed after the list is created.

---

### Think!

1. **What is a Python list?**
   - Can you describe what a list is and why it might be useful in programming?
   - How does a list differ from other data types like strings or integers?

2. **How do you create a list in Python?**
   - What syntax do you use to create a list?
   - Can you create a list that contains different data types, such as integers, strings, and floats?

3. **How do you access elements in a list?**
   - How would you access the first element in a list? How about the last element?
   - What happens if you try to access an index that is out of range?

4. **How do you modify elements in a list?**
   - How would you change the value of an element at a specific index?
   - How can you add new elements to a list?

5. **What are some common list methods?**
   - What methods can you use to add or remove elements from a list?
   - How would you sort a list or find the length of a list?

6. **What are some use cases for lists?**
   - When might you choose to use a list over other data types like tuples or dictionaries?

---

### Experimentation

#### **1. Creating Lists**

- **Create a list of numbers from 1 to 5.**


In [ ]:
#uncomment the codes below and fill the code with right syntax

# numbers =
# print(numbers)

- **Create a list containing different data types: a string, an integer, and a float.**

In [ ]:
# mixed_list =
# print(mixed_list)

#### **2. Accessing Elements**

- **Access the first and last elements of the `numbers` list.**

In [ ]:
  # first_element =
  # last_element =
  # print("First:", first_element, "Last:", last_element)


- **What happens if you try to access an index that doesn't exist?**

In [2]:
out_of_range = numbers[10]

IndexError: list index out of range


#### **3. Modifying Elements**

- **Change the second element of the `numbers` list to 10.**

In [4]:
# put your code in here:

print("Modified numbers:", numbers)

Modified numbers: [1, 10, 3, 4, 5]



- **Add a new element (6) to the end of the list.**   hint: use``` .append()  ``` method



In [ ]:
# put your code in here:

print("Appended:", numbers)


- **Insert a new element (2) at the beginning of the list.** hint: use ```
.insert()``` method


In [ ]:
# put your code in here:

print("Inserted at the beginning:", numbers)


#### **4. Removing Elements**

- **Remove the first occurrence of the number 10 from the list.**  hint: use``` .remove()  ``` method

In [ ]:
# put your code in here:

print("After removing 10:", numbers)

- **Remove the last element using `pop()`.**


In [ ]:
# put your code in here:

print("Popped element:", last_element, "Remaining list:", numbers)

#### **5. Common List Methods**

- **Sort the list of numbers.**  hint: use``` .sort()  ``` method

In [ ]:
# put your code in here:

print("Sorted numbers:", numbers)

- **Find the length of the list.**

In [ ]:
# put your code in here:

print("Length of list:", length)


---

### Python Dictionaries

A **dictionary** is a built-in Python data type that stores data in key-value pairs. Dictionaries are unordered, mutable, and indexed by keys, which can be of any immutable type (e.g., strings, numbers, tuples).

---

### Think!

1. **What is a Python dictionary?**
   - Can you explain what a dictionary is and why it might be useful in programming?
   - How does a dictionary differ from other data types like lists or tuples?

2. **How do you create a dictionary in Python?**
   - What syntax do you use to create a dictionary?
   - Can you create a dictionary with mixed data types for keys and values?

3. **How do you access values in a dictionary?**
   - How would you access the value associated with a specific key?
   - What happens if you try to access a key that doesn't exist?

4. **How do you modify values in a dictionary?**
   - How would you change the value associated with a specific key?
   - How can you add new key-value pairs to a dictionary?

5. **What are some common dictionary methods?**
   - What methods can you use to remove elements from a dictionary?
   - How would you iterate over the keys and values in a dictionary?

6. **What are some use cases for dictionaries?**
   - When might you choose to use a dictionary over other data types like lists or sets?

---

### Experimentation

#### **1. Creating Dictionaries**

- **Create a dictionary representing a person with keys for "name", "age", and "city".**


In [5]:
#uncomment the codes below and fill the code with right syntax

person = {
    "name": "Alice",
    "age": 23,
    "city": "Nebraska"
}
print(person)

{'name': 'Alice', 'age': 23, 'city': 'Nebraska'}


- **Create a dictionary with mixed data types for values.**

In [ ]:
mixed_dict = {
    "integer":
    "string":
    "list":
}
print(mixed_dict)

#### **2. Accessing Values**

- **Access the value associated with the "name" key in the `person` dictionary.**

In [ ]:
name =
print("Name:", name)

- **Access a value using the `get()` method, which provides a default value if the key is not found.**

In [9]:
height =
print("Height:", height)

Height: Unknown


#### **3. Modifying Values**
- **Change the "age" value in the `person` dictionary to 31.**

In [10]:
# put your code in here:

print("Updated person:", person)

Updated person: {'name': 'Alice', 'age': 31, 'city': 'Nebraska'}


- **Add a new key-value pair for "occupation".**

In [ ]:
# put your code in here:

print("With occupation:", person)

#### **4. Removing Elements**

- **Remove the "city" key-value pair from the `person` dictionary using `del`.**

In [11]:
# put your code in here:

print("After removing city:", person)

After removing city: {'name': 'Alice', 'age': 31}


- **Remove and return the "age" key-value pair using `pop()`.**

In [ ]:
# put your code in here:
age =
print("Popped age:", age, "Remaining dictionary:", person)

#### **5. Common Dictionary Methods**

- **Get a list of all keys in the dictionary.**  hint: use `.keys()` method



In [14]:
# put your code in here:
keys =
print("Keys:", keys)

Keys: ['name']



- **Iterate over key-value pairs in the dictionary.**

In [ ]:
for key, value in person.items():
  print(f"{key}: {value}")


---

### NumPy Arrays

**NumPy arrays** are a powerful data structure provided by the NumPy library in Python. They are similar to Python lists but offer more efficient storage and operations for numerical data. NumPy arrays are essential for scientific computing, data analysis, and machine learning tasks.

---

### Think!

1. **What is a NumPy array?**
   - How do NumPy arrays differ from Python lists?
   - Why are NumPy arrays preferred for numerical computations?

2. **How do you create a NumPy array?**
   - What syntax do you use to create a NumPy array?
   - Can you create a NumPy array from a Python list?

3. **How do you access elements in a NumPy array?**
   - How would you access the first element of a NumPy array?
   - How can you access a slice of a NumPy array?

4. **How do you modify elements in a NumPy array?**
   - How would you change the value of an element at a specific index?
   - Can you modify a subarray in place?

5. **What are some common NumPy array operations?**
   - How can you perform element-wise operations on NumPy arrays?
   - How would you calculate the mean or sum of elements in a NumPy array?

6. **What are some use cases for NumPy arrays?**
   - When might you choose to use a NumPy array over other data structures like lists or dictionaries?

---

### Experimentation

#### **1. Creating NumPy Arrays**

- **Create a NumPy array from a list of numbers.**


In [15]:
# import the numpy module

numbers = [1, 2, 3, 4, 5]

# create the numpy array
array =
print("NumPy array:", array)

NumPy array: [1 2 3 4 5]


- **Create a NumPy array of zeros with a specific shape (2,3).**

In [16]:
# put your code in here:
zeros_array =
print("Zeros array:\n", zeros_array)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]


- **Create a NumPy array of random numbers with shape (3,3).** hint: use `np.random.rand(3, 3)`



In [17]:
# put your code in here:

random_array =
print("Random array:\n", random_array)

Random array:
 [[0.74840899 0.49561266 0.94077898]
 [0.69476315 0.85731803 0.75030508]
 [0.6572383  0.74418521 0.20103607]]


#### **2. Accessing Elements**

- **Access the first element of the `array`.**

In [18]:
# put your code in here:
first_element =
print("First element:", first_element)

First element: 1



- **Access a subarray (slice) of the `array`.**

> slice it to be from element 2nd to 4th



In [19]:
# put your code in here:
subarray =
print("Subarray:", subarray)

Subarray: [2 3 4]


- **Access elements of a 2D array using row and column indices.**


In [35]:
matrix = np.array([[1, 2, 3], [4, 5, 6]]) #example 2d array

# Accessing element at row 0, column 1
element =
print("the matrix is\n", matrix, '\n')
print("Element at row 0, column 1:", element)

the matrix is
 [[1 2 3]
 [4 5 6]] 

Element at row 0, column 1: 2


#### **3. Modifying Elements**

- **Change the second element of the `array` to 10.**

In [21]:
# put your code in here:

print("Modified array:", array)

Modified array: [ 1 10  3  4  5]


- **Modify a subarray of a 2D array.**

In [22]:
# Modify the first row to be [7, 8, 9]

print("Modified matrix:\n", matrix)

Modified matrix:
 [[7 8 9]
 [4 5 6]]


#### **4. Common Operations**

- **Perform element-wise addition between two arrays.**

In [23]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# put your code in here:
sum_array =
print("Element-wise sum:", sum_array)

Element-wise sum: [5 7 9]


- **Calculate the mean and sum of a NumPy array.**

In [24]:
# put your code in here:
mean_value =
sum_value =
print("Mean:", mean_value, "Sum:", sum_value)

Mean: 4.6 Sum: 23



- **Use broadcasting to add a scalar to an array.**

In [25]:
# put your code in here: (scale adding by 5)

scalar_added =
print("Scalar added array:", scalar_added)

Scalar added array: [ 6 15  8  9 10]


#### **5. Reshaping Arrays**

- **Reshape a 1D array into a 2D array.**

In [37]:
#print the shape of array


(5,)

In [26]:
# reshape it to be (5,1) or (3,2)
reshaped_array =
print("Reshaped array:\n", reshaped_array)

Reshaped array:
 [[ 1]
 [10]
 [ 3]
 [ 4]
 [ 5]]


- **Flatten a 2D array back into a 1D array.** hint:use `.flatten()` method



In [ ]:
# flatten the matrix
flattened =
print("Flattened array:", flattened)